### ISSUE TITLE
Why the windows 10 cannot display all emoji

### ISSUE THREAD

**Issue by SmoothJM** [gaoac/cz-conventional-emoji#8]
![image](https://user-images.githubusercontent.com/44306149/116197842-bf97f400-a724-11eb-935a-cefde3016baf.png)

**Comment by gaoac** [comment]
This may be caused by the lack of Unicode character encoding in the current version of windows 10

**Comment by gaoac** [comment]
@SmoothJM This may be caused by the lack of Unicode character encoding in the current version of windows 10

**Comment by gaoac** [comment]
@SmoothJM Whether windows 10 has installed the Segoe UI Emoji font
